import { useEffect, useMemo, useRef, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { Alert, Badge, Button, Container, Drawer, Group, SegmentedControl, Select, SimpleGrid, Stack, Switch, Text, Title } from '@mantine/core'
import { batchScenarioById, batchScenarios, type BatchItem } from '../data/batch-scenarios'
import type { BatchItemResult } from '../lib/batch'
import './index.css'
export const Route = createFileRoute('/')({ component: Dashboard })
type ApiResult = { items?: BatchItemResult[]; elapsedMs?: number; error?: string }
const record = (value: unknown): Record<string, unknown> | undefined => typeof value === 'object' && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : undefined
const batchResponse = (value: unknown, expected: BatchItem[], lanes: Record<string, string>): ApiResult | undefined => {
  const root = record(value); const source = root && Array.isArray(root.items) ? root.items : undefined
  if (!root || !source || source.length !== expected.length) return undefined
  const expectedIds = new Set(expected.map((item) => item.id)); const seen = new Set<string>(); const items: BatchItemResult[] = []
  for (const candidate of source) { const item = record(candidate); if (!item || typeof item.id !== 'string' || !expectedIds.has(item.id) || seen.has(item.id)) return undefined; seen.add(item.id); const route = typeof item.route === 'string' && Object.hasOwn(lanes, item.route) ? item.route : undefined; const priority = typeof item.priority === 'number' && Number.isFinite(item.priority) && item.priority >= 0 && item.priority <= 2 ? item.priority : undefined; const confidence = typeof item.confidence === 'number' && Number.isFinite(item.confidence) && item.confidence >= 0 && item.confidence <= 1 ? item.confidence : undefined; const selectedProbability = typeof item.selectedProbability === 'number' && Number.isFinite(item.selectedProbability) && item.selectedProbability >= 0 && item.selectedProbability <= 1 ? item.selectedProbability : undefined; const error = typeof item.error === 'string' ? item.error : undefined; if ((!route || priority === undefined) && !error) return undefined; items.push({ id: item.id, route, priority, selectedProbability, confidence, error }) }
  return { items, elapsedMs: typeof root.elapsedMs === 'number' && Number.isFinite(root.elapsedMs) ? root.elapsedMs : undefined, error: typeof root.error === 'string' ? root.error : undefined }
}
const contexts: Record<string, string[]> = { support: ['顧客規模は未記載です', '締切は今週です'], sales: ['決裁者も確認予定です', '比較検討中です'], review: ['リリース候補です', '設計メモがあります'], incident: ['影響範囲を調査中です', '5分間継続しています'], documents: ['PDFで届いています', '期限が記載されています'], excuse: ['証人は猫です', '時計は見ていません'], cat: ['朝食前の出来事です', 'その後昼寝しました'], meeting: ['資料はありません', '結論は急ぎません'], loot: ['持ち主は不明です', '呪いは未確認です'], fridge: ['今夜の料理候補です', '洗い物は少なめ希望です'] }
const expand = (items: BatchItem[], count: number, scenarioId: string) => Array.from({ length: count }, (_, index) => { const base = items[index % items.length]; const n = Math.floor(index / items.length); return n ? { id: `${base.id}-${n + 1}`, text: `${base.text}。${contexts[scenarioId][(index + n) % contexts[scenarioId].length]}。` } : base })
const priority = (value?: number) => value === undefined ? '要確認' : ['低', '中', '高'][Math.round(value)] ?? '要確認'

function Dashboard() {
  const [mode, setMode] = useState<'work' | 'fun'>('work'); const visible = useMemo(() => batchScenarios.filter((item) => item.mode === mode), [mode])
  const [scenarioId, setScenarioId] = useState('support'); const scenario = batchScenarioById(scenarioId) ?? batchScenarios[0]
  const [count, setCount] = useState('20'); const items = useMemo(() => expand(scenario.samples, Number(count), scenario.id), [scenario, count])
  const [results, setResults] = useState<Record<string, BatchItemResult>>({}); const [running, setRunning] = useState(false); const [stopped, setStopped] = useState(false); const [error, setError] = useState<string>(); const [elapsed, setElapsed] = useState(0); const [lastBatch, setLastBatch] = useState<number>(); const [photo, setPhoto] = useState(false); const [selected, setSelected] = useState<BatchItem>()
  const controllerRef = useRef<AbortController | undefined>(undefined); const generation = useRef(0); const batchStarted = useRef<number | undefined>(undefined); const [clock, setClock] = useState(0)
  const reset = () => { generation.current += 1; controllerRef.current?.abort(); controllerRef.current = undefined; batchStarted.current = undefined; setRunning(false); setStopped(false); setResults({}); setError(undefined); setElapsed(0); setLastBatch(undefined) }
  useEffect(() => () => { generation.current += 1; controllerRef.current?.abort() }, [])
  useEffect(() => { if (!running) return; const timer = setInterval(() => setClock(performance.now()), 100); return () => clearInterval(timer) }, [running])
  const execute = async () => {
    const run = ++generation.current; const controller = new AbortController(); controllerRef.current = controller; setRunning(true); setStopped(false); setError(undefined)
    const pending = items.filter((item) => !results[item.id] || results[item.id].error)
    for (let start = 0; start < pending.length; start += 10) {
      if (run !== generation.current || controller.signal.aborted) break
      const group = pending.slice(start, start + 10); const began = performance.now(); batchStarted.current = began
      try {
        const response = await fetch('/api/batch', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ scenarioId: scenario.id, items: group }), signal: controller.signal })
        const raw = response.headers.get('content-type')?.includes('application/json') ? await response.json() as unknown : undefined
        const data = batchResponse(raw, group, scenario.lanes); const rawRecord = record(raw); const serverError = typeof rawRecord?.error === 'string' ? rawRecord.error : undefined
        if (run !== generation.current) break
        const duration = performance.now() - began; setElapsed((value) => value + duration); setLastBatch(duration); batchStarted.current = undefined
        if (!response.ok || !data?.items) { setError(serverError ?? data?.error ?? '通信または評価サービスに問題が発生しました。'); setStopped(true); break }
        setResults((previous) => ({ ...previous, ...Object.fromEntries(data.items!.map((item) => [item.id, item])) }))
      } catch { if (run !== generation.current || controller.signal.aborted) break; const duration = performance.now() - began; setElapsed((value) => value + duration); setLastBatch(duration); batchStarted.current = undefined; setError('通信または評価サービスに問題が発生しました。'); setStopped(true); break }
    }
    if (run === generation.current) { setRunning(false); controllerRef.current = undefined }
  }
  const completed = items.filter((item) => results[item.id] && !results[item.id].error).length; const displayedElapsed = elapsed + (running && batchStarted.current ? Math.max(0, clock - batchStarted.current) : 0); const rate = displayedElapsed ? (completed / (displayedElapsed / 1000)).toFixed(1) : '—'; const review = items.filter((item) => { const result = results[item.id]; const certainty = result?.selectedProbability ?? result?.confidence; return result && (!result.route || result.priority === undefined || result.error || certainty === undefined || certainty < .8) })
  return <main className={`jev-shell ${photo ? 'shooting' : ''}`}><Container size="xl"><nav className="jev-nav"><Group justify="space-between"><Text className="jev-mark">Jev 実験室</Text><Badge variant="outline" color="orange">Workers · Vercel AI Gateway</Badge></Group></nav><section className="batch-hero"><Text className="jev-kicker">HIGH-THROUGHPUT JUDGMENT</Text><h1 className="jev-title">大量の判断を、<br />一気に。</h1><Text className="jev-subtitle">10件ずつ一括判定。通信込みの実測で、仕分けの流れを見える化します。</Text></section>
    <Group justify="space-between" mb="md"><SegmentedControl value={mode} disabled={running} onChange={(value) => { reset(); setMode(value as 'work' | 'fun'); setScenarioId(batchScenarios.find((item) => item.mode === value)?.id ?? scenarioId) }} data={[{ label: '実務', value: 'work' }, { label: '無駄遣い', value: 'fun' }]} color={mode === 'fun' ? 'orange' : 'indigo'} /><Group><Select value={count} disabled={running} onChange={(value) => { reset(); if (value) setCount(value) }} data={['10', '20', '50', '100']} w={100} /><Switch label="撮影" checked={photo} onChange={(event) => setPhoto(event.currentTarget.checked)} color="orange" /></Group></Group>
    <section className="scenario-list">{visible.map((item, index) => <button key={item.id} disabled={running} className={`scenario-button ${item.id === scenario.id ? 'selected' : ''} ${item.mode === 'fun' ? 'fun' : ''}`} onClick={() => { reset(); setScenarioId(item.id) }}><span className="scenario-number">{String(index + 1).padStart(2, '0')}</span><span className="scenario-name">{item.title}</span></button>)}</section>
    <SimpleGrid cols={{ base: 1, sm: 3 }} spacing="md" my="lg" className="metrics"><div><Text>完了件数</Text><strong>{completed}<small> / {items.length}</small></strong></div><div><Text>実測経過</Text><strong>{(displayedElapsed / 1000).toFixed(1)}<small> 秒</small></strong></div><div><Text>件毎秒</Text><strong>{rate}</strong></div></SimpleGrid>
    <Group mb="md"><Button onClick={execute} loading={running} disabled={running || completed === items.length}>{completed ? '残りを再開' : '仕分け開始'}</Button><Button variant="default" disabled={!running} onClick={() => { generation.current += 1; if (batchStarted.current !== undefined) { const duration = performance.now() - batchStarted.current; setElapsed((value) => value + duration); setLastBatch(duration); batchStarted.current = undefined } controllerRef.current?.abort(); setRunning(false); setStopped(true) }}>停止</Button><Button variant="subtle" color="gray" disabled={running} onClick={reset}>リセット</Button>{lastBatch && <Text size="sm" c="dimmed">直近バッチ {lastBatch.toFixed(0)}ms · 通信込み実測</Text>}</Group>
    {error && <Alert color="red" title="仕分けを停止しました">{error}</Alert>}{stopped && !error && <Alert color="yellow">停止中です。残りを再開できます。</Alert>}
    <SimpleGrid cols={{ base: 2, md: 5 }} spacing="xs" className="lane-summary" mb="md">{Object.entries(scenario.lanes).map(([key, label]) => <div key={key}><Text size="xs">{label}</Text><strong>{items.filter((item) => { const result = results[item.id]; return result?.route === key && !review.some((candidate) => candidate.id === item.id) }).length}</strong></div>)}<div><Text size="xs">要確認</Text><strong>{review.length}</strong></div></SimpleGrid>
    <section className="queue"><Group justify="space-between"><Title order={2}>受信トレイ</Title><Text c="dimmed">架空デモデータ {items.length}件</Text></Group><div className="item-grid">{items.map((item) => { const result = results[item.id]; const certainty = result?.selectedProbability ?? result?.confidence; return <article className={`item-card ${result ? 'done' : ''}`} key={item.id} role="button" tabIndex={0} onClick={() => setSelected(item)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelected(item) } }}><Text size="xs" c="dimmed">{item.id}</Text><Text lineClamp={3}>{item.text}</Text>{result && <Badge mt="xs" color={result.error || certainty === undefined || certainty < .8 ? 'yellow' : 'indigo'}>{result.error ? '要確認' : `${result.route ? scenario.lanes[result.route] : '要確認'} · ${priority(result.priority)}`}</Badge>}</article> })}</div></section>
    <section className="review-lane"><Text fw={700}>要確認 {review.length}件</Text><Text size="sm">分類確率80%未満・欠落・評価エラーをここに残します。無料枠の429では自動停止します。</Text></section>
    <Drawer opened={Boolean(selected)} onClose={() => setSelected(undefined)} title="項目の詳細" position="right"><Stack>{selected && <><Text size="xs" c="dimmed">{selected.id}</Text><Text>{selected.text}</Text><Text fw={700}>{results[selected.id]?.route ? scenario.lanes[results[selected.id].route!] : '要確認'} · 優先度 {priority(results[selected.id]?.priority)}</Text><Text>分類確率: {results[selected.id]?.selectedProbability === undefined ? '未取得' : `${Math.round(results[selected.id].selectedProbability! * 100)}%`}</Text><Text>モデル信頼度: {results[selected.id]?.confidence === undefined ? '未取得' : `${Math.round(results[selected.id].confidence! * 100)}%`}</Text><Text size="sm" c="dimmed">{results[selected.id]?.error ?? '要確認判定は分類確率を優先し、欠落時はモデル信頼度を使います。'}</Text></>}</Stack></Drawer>
  </Container></main>
}
