/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSqlRouteImport } from './routes/api/sql'
import { Route as ApiSchemaRouteImport } from './routes/api/schema'
import { Route as ApiResetRouteImport } from './routes/api/reset'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiTasksIndexRouteImport } from './routes/api/tasks/index'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSqlRoute = ApiSqlRouteImport.update({
  id: '/api/sql',
  path: '/api/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaRoute = ApiSchemaRouteImport.update({
  id: '/api/schema',
  path: '/api/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetRoute = ApiResetRouteImport.update({
  id: '/api/reset',
  path: '/api/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIndexRoute = ApiTasksIndexRouteImport.update({
  id: '/api/tasks/',
  path: '/api/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/api/tasks/$id',
  path: '/api/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/reset': typeof ApiResetRoute
  '/api/schema': typeof ApiSchemaRoute
  '/api/sql': typeof ApiSqlRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/reset': typeof ApiResetRoute
  '/api/schema': typeof ApiSchemaRoute
  '/api/sql': typeof ApiSqlRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/tasks': typeof ApiTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/reset': typeof ApiResetRoute
  '/api/schema': typeof ApiSchemaRoute
  '/api/sql': typeof ApiSqlRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/categories'
    | '/api/reset'
    | '/api/schema'
    | '/api/sql'
    | '/api/tasks/$id'
    | '/api/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/categories'
    | '/api/reset'
    | '/api/schema'
    | '/api/sql'
    | '/api/tasks/$id'
    | '/api/tasks'
  id:
    | '__root__'
    | '/'
    | '/api/categories'
    | '/api/reset'
    | '/api/schema'
    | '/api/sql'
    | '/api/tasks/$id'
    | '/api/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiResetRoute: typeof ApiResetRoute
  ApiSchemaRoute: typeof ApiSchemaRoute
  ApiSqlRoute: typeof ApiSqlRoute
  ApiTasksIdRoute: typeof ApiTasksIdRoute
  ApiTasksIndexRoute: typeof ApiTasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sql': {
      id: '/api/sql'
      path: '/api/sql'
      fullPath: '/api/sql'
      preLoaderRoute: typeof ApiSqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema': {
      id: '/api/schema'
      path: '/api/schema'
      fullPath: '/api/schema'
      preLoaderRoute: typeof ApiSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset': {
      id: '/api/reset'
      path: '/api/reset'
      fullPath: '/api/reset'
      preLoaderRoute: typeof ApiResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/': {
      id: '/api/tasks/'
      path: '/api/tasks'
      fullPath: '/api/tasks/'
      preLoaderRoute: typeof ApiTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/api/tasks/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiResetRoute: ApiResetRoute,
  ApiSchemaRoute: ApiSchemaRoute,
  ApiSqlRoute: ApiSqlRoute,
  ApiTasksIdRoute: ApiTasksIdRoute,
  ApiTasksIndexRoute: ApiTasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
