/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClosetRouteImport } from './routes/closet'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImgIdRouteImport } from './routes/api/img/$id'

const ClosetRoute = ClosetRouteImport.update({
  id: '/closet',
  path: '/closet',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgIdRoute = ApiImgIdRouteImport.update({
  id: '/api/img/$id',
  path: '/api/img/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/closet': typeof ClosetRoute
  '/api/img/$id': typeof ApiImgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/closet': typeof ClosetRoute
  '/api/img/$id': typeof ApiImgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/closet': typeof ClosetRoute
  '/api/img/$id': typeof ApiImgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/architecture' | '/closet' | '/api/img/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/architecture' | '/closet' | '/api/img/$id'
  id: '__root__' | '/' | '/architecture' | '/closet' | '/api/img/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ClosetRoute: typeof ClosetRoute
  ApiImgIdRoute: typeof ApiImgIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/closet': {
      id: '/closet'
      path: '/closet'
      fullPath: '/closet'
      preLoaderRoute: typeof ClosetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img/$id': {
      id: '/api/img/$id'
      path: '/api/img/$id'
      fullPath: '/api/img/$id'
      preLoaderRoute: typeof ApiImgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  ClosetRoute: ClosetRoute,
  ApiImgIdRoute: ApiImgIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
