/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEvaluateRouteImport } from './routes/api.evaluate'
import { Route as ApiBatchRouteImport } from './routes/api.batch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluateRoute = ApiEvaluateRouteImport.update({
  id: '/api/evaluate',
  path: '/api/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBatchRoute = ApiBatchRouteImport.update({
  id: '/api/batch',
  path: '/api/batch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/batch': typeof ApiBatchRoute
  '/api/evaluate': typeof ApiEvaluateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/batch': typeof ApiBatchRoute
  '/api/evaluate': typeof ApiEvaluateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/batch': typeof ApiBatchRoute
  '/api/evaluate': typeof ApiEvaluateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/batch' | '/api/evaluate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/batch' | '/api/evaluate'
  id: '__root__' | '/' | '/api/batch' | '/api/evaluate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBatchRoute: typeof ApiBatchRoute
  ApiEvaluateRoute: typeof ApiEvaluateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluate': {
      id: '/api/evaluate'
      path: '/api/evaluate'
      fullPath: '/api/evaluate'
      preLoaderRoute: typeof ApiEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/batch': {
      id: '/api/batch'
      path: '/api/batch'
      fullPath: '/api/batch'
      preLoaderRoute: typeof ApiBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBatchRoute: ApiBatchRoute,
  ApiEvaluateRoute: ApiEvaluateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
